### ISSUE TITLE
travis building mac os x

### ISSUE THREAD

**Issue by the-real-neil** [rubicks/quantlib#1]
@noo-space , I've taken the liberty of creating a .travis.yml file that demonstrates how to compile quantlib from source on Mac OS X. Mac OS X is a troublesome compilation target since it's, well, proprietary.

**Comment by rubicks** [comment]
@noo-space , until we can get some manner of chat going between us, I'm going to use the comments on this github issue as a communication medium. I have a vested interest in helping you because I use autotools extensively and want to see more developers use them.

**Comment by rubicks** [comment]
@noo-space , speaking of chats, you're more than welcome to find me on google hangouts: naroza@gmail.com . I can also access most IRC networks, if you prefer that.

**Comment by noo-space** [comment]
Hi rubicks, I just sent you a chat request on google hangouts.
Best regards,
James
